exports.twitter =
  consumer_key : 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  consumer_secret : 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  token_secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

exports.googlePlaces = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

exports.hp = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

exports.watson =
  username: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  password: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
